language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t dockerbaxhen.azurecr.io/azure-docker -f Dockerfile.dev .

script:
  - docker run -e CI=true dockerbaxhen.azurecr.io/azure-docker npm run test
    docker login -u="$AZURE_USERNAME" -p="$AZURE_PASSWORD";
    docker push dockerbaxhen.azurecr.io/azure-docker;
  on:
    branch: master
