language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t baxhen/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true baxhen/docker-react npm run test

deploy:
  provider: azure_web_apps
  username: $AZURE_WA_USERNAME
  password: $AZURE_WA_PASSWORD
  site: $AZURE_WA_SITE
  slot: $AZURE_WA_SLOT
  on:
    branch: master
